### ISSUE TITLE
add an environment for reproducibility

### ISSUE THREAD

**Issue by priamai** [ananyalahiri2003/sigma_attack#1]
We always work with poetry or pyenv to make sure the environment can be reproducible to other developers.
Can you add:

- poetry project file
- requirements file
- python version

A simple README with explanation of usage.

I can see a few dependencies there: pandas, click, sklearn.

Thanks.

**Comment by ananyalahiri2003** [comment]
Hi I have now added pyproject.toml, poetry.lock, a README file. 
Let me know what else needed, thanks

**Comment by ananyalahiri2003** [comment]
I could install the poetry env locally with python ^3.9 thanks

**Comment by priamai** [comment]
Great thanks.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by priamai** [comment]
Poetry added.
